//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ApiSampleFramework.message {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ApiServiceFxiMessageSoap", Namespace="urn:ApiServiceFxiMessage")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(FaxinMessage))]
    public partial class ApiServiceFxiMessage : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private UsernameToken usernameTokenValueField;
        
        private System.Threading.SendOrPostCallback countFaxesOperationCompleted;
        
        private System.Threading.SendOrPostCallback listFaxesOperationCompleted;
        
        private System.Threading.SendOrPostCallback downloadFaxOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteFaxOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ApiServiceFxiMessage() {
            this.Url = global::ApiSampleFramework.Properties.Settings.Default.ApiSampleFramework_message_ApiServiceFxiMessage;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public UsernameToken UsernameTokenValue {
            get {
                return this.usernameTokenValueField;
            }
            set {
                this.usernameTokenValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event countFaxesCompletedEventHandler countFaxesCompleted;
        
        /// <remarks/>
        public event listFaxesCompletedEventHandler listFaxesCompleted;
        
        /// <remarks/>
        public event downloadFaxCompletedEventHandler downloadFaxCompleted;
        
        /// <remarks/>
        public event deleteFaxCompletedEventHandler deleteFaxCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UsernameTokenValue")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("#countFaxes", RequestNamespace="urn:ApiServiceFxiMessage", ResponseNamespace="urn:ApiServiceFxiMessage")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public ApiResponseItemsCount countFaxes(ApiRequestCountFaxes listRequest) {
            object[] results = this.Invoke("countFaxes", new object[] {
                        listRequest});
            return ((ApiResponseItemsCount)(results[0]));
        }
        
        /// <remarks/>
        public void countFaxesAsync(ApiRequestCountFaxes listRequest) {
            this.countFaxesAsync(listRequest, null);
        }
        
        /// <remarks/>
        public void countFaxesAsync(ApiRequestCountFaxes listRequest, object userState) {
            if ((this.countFaxesOperationCompleted == null)) {
                this.countFaxesOperationCompleted = new System.Threading.SendOrPostCallback(this.OncountFaxesOperationCompleted);
            }
            this.InvokeAsync("countFaxes", new object[] {
                        listRequest}, this.countFaxesOperationCompleted, userState);
        }
        
        private void OncountFaxesOperationCompleted(object arg) {
            if ((this.countFaxesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.countFaxesCompleted(this, new countFaxesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UsernameTokenValue")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("#listFaxes", RequestNamespace="urn:ApiServiceFxiMessage", ResponseNamespace="urn:ApiServiceFxiMessage")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public ApiResponseListFaxes listFaxes(ApiRequestListFaxes listRequest) {
            object[] results = this.Invoke("listFaxes", new object[] {
                        listRequest});
            return ((ApiResponseListFaxes)(results[0]));
        }
        
        /// <remarks/>
        public void listFaxesAsync(ApiRequestListFaxes listRequest) {
            this.listFaxesAsync(listRequest, null);
        }
        
        /// <remarks/>
        public void listFaxesAsync(ApiRequestListFaxes listRequest, object userState) {
            if ((this.listFaxesOperationCompleted == null)) {
                this.listFaxesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistFaxesOperationCompleted);
            }
            this.InvokeAsync("listFaxes", new object[] {
                        listRequest}, this.listFaxesOperationCompleted, userState);
        }
        
        private void OnlistFaxesOperationCompleted(object arg) {
            if ((this.listFaxesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listFaxesCompleted(this, new listFaxesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UsernameTokenValue")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("#downloadFax", RequestNamespace="urn:ApiServiceFxiMessage", ResponseNamespace="urn:ApiServiceFxiMessage")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public ApiResponseDocPreview downloadFax(string messageRef, bool isPDF) {
            object[] results = this.Invoke("downloadFax", new object[] {
                        messageRef,
                        isPDF});
            return ((ApiResponseDocPreview)(results[0]));
        }
        
        /// <remarks/>
        public void downloadFaxAsync(string messageRef, bool isPDF) {
            this.downloadFaxAsync(messageRef, isPDF, null);
        }
        
        /// <remarks/>
        public void downloadFaxAsync(string messageRef, bool isPDF, object userState) {
            if ((this.downloadFaxOperationCompleted == null)) {
                this.downloadFaxOperationCompleted = new System.Threading.SendOrPostCallback(this.OndownloadFaxOperationCompleted);
            }
            this.InvokeAsync("downloadFax", new object[] {
                        messageRef,
                        isPDF}, this.downloadFaxOperationCompleted, userState);
        }
        
        private void OndownloadFaxOperationCompleted(object arg) {
            if ((this.downloadFaxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.downloadFaxCompleted(this, new downloadFaxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UsernameTokenValue")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("#deleteFax", RequestNamespace="urn:ApiServiceFxiMessage", ResponseNamespace="urn:ApiServiceFxiMessage")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public ApiResponse deleteFax(string messageRef) {
            object[] results = this.Invoke("deleteFax", new object[] {
                        messageRef});
            return ((ApiResponse)(results[0]));
        }
        
        /// <remarks/>
        public void deleteFaxAsync(string messageRef) {
            this.deleteFaxAsync(messageRef, null);
        }
        
        /// <remarks/>
        public void deleteFaxAsync(string messageRef, object userState) {
            if ((this.deleteFaxOperationCompleted == null)) {
                this.deleteFaxOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteFaxOperationCompleted);
            }
            this.InvokeAsync("deleteFax", new object[] {
                        messageRef}, this.deleteFaxOperationCompleted, userState);
        }
        
        private void OndeleteFaxOperationCompleted(object arg) {
            if ((this.deleteFaxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteFaxCompleted(this, new deleteFaxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ApiServiceFxiMessage")]
    public partial class UsernameToken : SoapHeader {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ApiServiceFxiMessage")]
    public partial class FaxinMessage {
        
        private string refIDField;
        
        private string recipientE164Field;
        
        private string senderE164Field;
        
        private StateTransport stateField;
        
        private StateCodes stateExField;
        
        private bool stateExFieldSpecified;
        
        private string stateMessageField;
        
        private System.DateTime dateReceivedField;
        
        private int durationCallField;
        
        private bool durationCallFieldSpecified;
        
        private int durationFaxField;
        
        private bool durationFaxFieldSpecified;
        
        private string localSIDField;
        
        private string remoteSIDField;
        
        private int pagesField;
        
        private bool pagesFieldSpecified;
        
        private int speedField;
        
        private bool speedFieldSpecified;
        
        private bool ecmField;
        
        private bool ecmFieldSpecified;
        
        private FaxQuality qualityField;
        
        private bool qualityFieldSpecified;
        
        private FaxCompression compressionField;
        
        private bool compressionFieldSpecified;
        
        private bool hasFileField;
        
        /// <remarks/>
        public string refID {
            get {
                return this.refIDField;
            }
            set {
                this.refIDField = value;
            }
        }
        
        /// <remarks/>
        public string recipientE164 {
            get {
                return this.recipientE164Field;
            }
            set {
                this.recipientE164Field = value;
            }
        }
        
        /// <remarks/>
        public string senderE164 {
            get {
                return this.senderE164Field;
            }
            set {
                this.senderE164Field = value;
            }
        }
        
        /// <remarks/>
        public StateTransport state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public StateCodes stateEx {
            get {
                return this.stateExField;
            }
            set {
                this.stateExField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool stateExSpecified {
            get {
                return this.stateExFieldSpecified;
            }
            set {
                this.stateExFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string stateMessage {
            get {
                return this.stateMessageField;
            }
            set {
                this.stateMessageField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dateReceived {
            get {
                return this.dateReceivedField;
            }
            set {
                this.dateReceivedField = value;
            }
        }
        
        /// <remarks/>
        public int durationCall {
            get {
                return this.durationCallField;
            }
            set {
                this.durationCallField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool durationCallSpecified {
            get {
                return this.durationCallFieldSpecified;
            }
            set {
                this.durationCallFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int durationFax {
            get {
                return this.durationFaxField;
            }
            set {
                this.durationFaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool durationFaxSpecified {
            get {
                return this.durationFaxFieldSpecified;
            }
            set {
                this.durationFaxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string localSID {
            get {
                return this.localSIDField;
            }
            set {
                this.localSIDField = value;
            }
        }
        
        /// <remarks/>
        public string remoteSID {
            get {
                return this.remoteSIDField;
            }
            set {
                this.remoteSIDField = value;
            }
        }
        
        /// <remarks/>
        public int pages {
            get {
                return this.pagesField;
            }
            set {
                this.pagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool pagesSpecified {
            get {
                return this.pagesFieldSpecified;
            }
            set {
                this.pagesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int speed {
            get {
                return this.speedField;
            }
            set {
                this.speedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool speedSpecified {
            get {
                return this.speedFieldSpecified;
            }
            set {
                this.speedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool ecm {
            get {
                return this.ecmField;
            }
            set {
                this.ecmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool ecmSpecified {
            get {
                return this.ecmFieldSpecified;
            }
            set {
                this.ecmFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FaxQuality quality {
            get {
                return this.qualityField;
            }
            set {
                this.qualityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool qualitySpecified {
            get {
                return this.qualityFieldSpecified;
            }
            set {
                this.qualityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FaxCompression compression {
            get {
                return this.compressionField;
            }
            set {
                this.compressionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool compressionSpecified {
            get {
                return this.compressionFieldSpecified;
            }
            set {
                this.compressionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool hasFile {
            get {
                return this.hasFileField;
            }
            set {
                this.hasFileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ApiServiceFxiMessage")]
    public enum StateTransport {
        
        /// <remarks/>
        UNKNOWN,
        
        /// <remarks/>
        READY,
        
        /// <remarks/>
        ASSIGNED,
        
        /// <remarks/>
        QUEUED,
        
        /// <remarks/>
        PREPARING,
        
        /// <remarks/>
        PLACED,
        
        /// <remarks/>
        DIALING,
        
        /// <remarks/>
        RINGING,
        
        /// <remarks/>
        CONNECTED,
        
        /// <remarks/>
        NEGOTIATING,
        
        /// <remarks/>
        TRAINING,
        
        /// <remarks/>
        TRANSMITTING,
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        PAUSED,
        
        /// <remarks/>
        FAILED,
        
        /// <remarks/>
        ABORTED,
        
        /// <remarks/>
        CANCELLED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ApiServiceFxiMessage")]
    public enum StateCodes {
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        API_FUNCTION_MISSING,
        
        /// <remarks/>
        API_FUNCTION_UNKNOWN,
        
        /// <remarks/>
        API_FUNCTION_ACCESS_DENIED,
        
        /// <remarks/>
        API_AGENT_MISSING,
        
        /// <remarks/>
        API_AGENT_NOT_FOUND,
        
        /// <remarks/>
        API_AGENT_DEACTIVATED,
        
        /// <remarks/>
        API_AGENT_KEY_NOT_MATCH,
        
        /// <remarks/>
        API_CUSTOMER_MISSING,
        
        /// <remarks/>
        API_CUSTOMER_NOT_FOUND,
        
        /// <remarks/>
        API_CUSTOMER_DEACTIVATED,
        
        /// <remarks/>
        API_CUSTOMER_KEY_NOT_MATCH,
        
        /// <remarks/>
        API_CUSTOMER_FEATURE_ACCESS_DENIED,
        
        /// <remarks/>
        API_KEY_MISSING,
        
        /// <remarks/>
        API_KEY_NOT_FOUND,
        
        /// <remarks/>
        API_KEY_DEACTIVATED,
        
        /// <remarks/>
        API_KEY_SECRET_NOT_MATCH,
        
        /// <remarks/>
        API_REQUEST_INCOMPLETE,
        
        /// <remarks/>
        API_REQUEST_FAILURE,
        
        /// <remarks/>
        API_REQUEST_VALIDATE,
        
        /// <remarks/>
        FILE_NOT_FOUND,
        
        /// <remarks/>
        FILE_DELETED,
        
        /// <remarks/>
        FILE_ACCESS_DENIED,
        
        /// <remarks/>
        FILE_STORAGE_MISSING,
        
        /// <remarks/>
        FILE_STORAGE_SIZE_MISMATCH,
        
        /// <remarks/>
        FILE_STORAGE_READ_ERROR,
        
        /// <remarks/>
        FILE_EXISTS,
        
        /// <remarks/>
        CUSTOMER_DELETED,
        
        /// <remarks/>
        CUSTOMER_NOT_CONFIRMED,
        
        /// <remarks/>
        CUSTOMER_BLOCKED,
        
        /// <remarks/>
        CUSTOMER_INACTIVE,
        
        /// <remarks/>
        CUSTOMER_WRONG_PASSWORD,
        
        /// <remarks/>
        CUSTOMER_PASSWORD_NOT_MATCH,
        
        /// <remarks/>
        CUSTOMER_CURRENT_PASSWORD_NOT_MATCH,
        
        /// <remarks/>
        CUSTOMER_EMAIL_IN_USE,
        
        /// <remarks/>
        CUSTOMER_SOCIAL_IN_USE,
        
        /// <remarks/>
        FILE_REFERENCE_DUPLICATE,
        
        /// <remarks/>
        FILE_STORAGE_COPY,
        
        /// <remarks/>
        FILE_INTEGRITY_FAILURE,
        
        /// <remarks/>
        FILE_FORMAT_UNSUPPORTED,
        
        /// <remarks/>
        FILE_FORMAT_EXCEPTION,
        
        /// <remarks/>
        FILE_FORMAT_UNKNOWN,
        
        /// <remarks/>
        FILE_DOWNLOAD_ERROR,
        
        /// <remarks/>
        FILE_VALIDATE_ERROR,
        
        /// <remarks/>
        FILE_OPEN_ERROR,
        
        /// <remarks/>
        FILE_THUMB_ERROR,
        
        /// <remarks/>
        DATABASE_RECORD_SAVE,
        
        /// <remarks/>
        DATABASE_QUERY_EXECUTE,
        
        /// <remarks/>
        DATABASE_QUERY_RESULT_SAVE,
        
        /// <remarks/>
        NUMBER_COUNTRY_UNKNOWN,
        
        /// <remarks/>
        NUMBER_NO_DIALING_RULE,
        
        /// <remarks/>
        NUMBER_NO_PRICE_RULE,
        
        /// <remarks/>
        COUNTRY_WRONG_ISO2,
        
        /// <remarks/>
        COUNTRY_NOT_SUPPORTED,
        
        /// <remarks/>
        COUNTRY_NO_ROUTE,
        
        /// <remarks/>
        EMPTY_RESULT,
        
        /// <remarks/>
        NUMBER_BLOCKED,
        
        /// <remarks/>
        NUMBER_UNOBTAINABLE,
        
        /// <remarks/>
        UNALLOCATED_NUMBER,
        
        /// <remarks/>
        INVALID_NUMBER,
        
        /// <remarks/>
        NUMBER_UNSUPPORTED,
        
        /// <remarks/>
        CALL_ABORTED,
        
        /// <remarks/>
        CALL_REJECTED,
        
        /// <remarks/>
        CALL_PLACE_ERROR,
        
        /// <remarks/>
        CALL_CREATE_ERROR,
        
        /// <remarks/>
        LINE_ATTACH,
        
        /// <remarks/>
        LINE_RESET,
        
        /// <remarks/>
        LINE_CAP_FAX,
        
        /// <remarks/>
        LINE_CAP_VOICE,
        
        /// <remarks/>
        LINE_SET_TSID,
        
        /// <remarks/>
        LINE_UNAUTHORIZED,
        
        /// <remarks/>
        LINE_REQUEST_TIMEOUT,
        
        /// <remarks/>
        DESTINATION_UNREACHIBLE,
        
        /// <remarks/>
        DIALING_ERROR,
        
        /// <remarks/>
        GATEWAY_TIMEOUT,
        
        /// <remarks/>
        ISDN_NETWORK_FAILURE,
        
        /// <remarks/>
        BUSY,
        
        /// <remarks/>
        NO_ANSWER,
        
        /// <remarks/>
        NO_DIAL_TONE,
        
        /// <remarks/>
        RECEIVER_INCOMPATIBLE,
        
        /// <remarks/>
        TEMPORARILY_UNAVAILABLE,
        
        /// <remarks/>
        TRANSMISSION_ABORTED,
        
        /// <remarks/>
        TRANSMISSION_EARLY_HANGUP,
        
        /// <remarks/>
        TRANSMISSION_ERROR,
        
        /// <remarks/>
        NEGOTIATION_FAILED,
        
        /// <remarks/>
        NOT_FAX_MACHINE,
        
        /// <remarks/>
        VOICE_ANSWER,
        
        /// <remarks/>
        DELIVERY_FAILURE,
        
        /// <remarks/>
        MESSAGE_REFERENCE_DUPLICATE,
        
        /// <remarks/>
        FAXJOB_NOT_FOUND,
        
        /// <remarks/>
        FAXJOB_NOT_FAILED,
        
        /// <remarks/>
        FAXJOB_NOT_WAITING,
        
        /// <remarks/>
        FAXTRANSPORT_NOT_FOUND,
        
        /// <remarks/>
        FAXTRANSPORT_NOT_WAITING,
        
        /// <remarks/>
        CONTAINER_EXISTS,
        
        /// <remarks/>
        CONTAINER_NOT_FOUND,
        
        /// <remarks/>
        CONTAINER_DELETED,
        
        /// <remarks/>
        CONTAINER_ACCESS_DENIED,
        
        /// <remarks/>
        CONTAINER_DOCUMENT_DUPLICATE,
        
        /// <remarks/>
        CONTAINER_PAGES_LIMIT_EXCEEDED,
        
        /// <remarks/>
        COVER_TEMPLATE_NOT_FOUND,
        
        /// <remarks/>
        COVER_TEMPLATE_DELETED,
        
        /// <remarks/>
        COVER_TEMPLATE_ACCESS_DENIED,
        
        /// <remarks/>
        FAXPRICE_NOT_FOUND,
        
        /// <remarks/>
        RESUBMIT_FAILED,
        
        /// <remarks/>
        DID_NUMBER_LOCKED,
        
        /// <remarks/>
        DID_SOURCE_NOT_FAXIN,
        
        /// <remarks/>
        DID_CUSTOMER_NOT_MATCH,
        
        /// <remarks/>
        DID_WRONG_FAXIN_STATE,
        
        /// <remarks/>
        DID_GROUP_NOT_CONNECTED,
        
        /// <remarks/>
        DID_EXTEND_TOO_EARLY,
        
        /// <remarks/>
        DID_ORDER_PENDING_ACTIVATION,
        
        /// <remarks/>
        FILE_PREVIEW_NOT_READY,
        
        /// <remarks/>
        FILE_CONVERTION_FAILED,
        
        /// <remarks/>
        FILE_PAGES_LIMIT_EXCEEDED,
        
        /// <remarks/>
        COMMON_EMAIL_SEND_ERROR,
        
        /// <remarks/>
        QUEUE_TASK_ABORTED,
        
        /// <remarks/>
        FILE_TIFF_DEPTH_VALIDATION,
        
        /// <remarks/>
        FILE_TIFF_FORMAT_VALIDATION,
        
        /// <remarks/>
        FILE_TIFF_QUALITY_VALIDATION,
        
        /// <remarks/>
        FILE_TIFF_PAGES_VALIDATION,
        
        /// <remarks/>
        FILE_TIFF_WIDTH_VALIDATION,
        
        /// <remarks/>
        FILE_TIFF_HEIGHT_VALIDATION,
        
        /// <remarks/>
        NUMBER_ADDRESS_NOT_REQUIRED,
        
        /// <remarks/>
        NUMBER_OUT_OF_STOCK,
        
        /// <remarks/>
        NUMBER_GROUP_NOT_AVAILABLE,
        
        /// <remarks/>
        NUMBER_ORDER_FAILURE,
        
        /// <remarks/>
        NUMBER_SETUP_FAILURE,
        
        /// <remarks/>
        NUMBER_ADDRESS_FAILURE,
        
        /// <remarks/>
        NUMBER_PROVIDER_NOT_RECOGNIZED,
        
        /// <remarks/>
        SESSION_TOKEN_MISMATCH,
        
        /// <remarks/>
        SESSION_NOT_FOUND,
        
        /// <remarks/>
        SESSION_EXPIRED,
        
        /// <remarks/>
        CONFIRM_TOKEN_NOT_FOUND,
        
        /// <remarks/>
        CONFIRM_TOKEN_TYPE_MISMATCH,
        
        /// <remarks/>
        CONFIRM_TOKEN_SOURCE_MISMATCH,
        
        /// <remarks/>
        CONFIRM_TOKEN_USER_MISMATCH,
        
        /// <remarks/>
        CONFIRM_TOKEN_EXPIRED,
        
        /// <remarks/>
        CONFIRM_TOKEN_VALIDATED,
        
        /// <remarks/>
        CONFIRM_TOKEN_INVALIDATED,
        
        /// <remarks/>
        CONFIRM_TOKEN_CLOSED,
        
        /// <remarks/>
        SEND_SMS_FREQUENCY_EXCEEDED,
        
        /// <remarks/>
        CONTACT_GROUP_IN_USE,
        
        /// <remarks/>
        CONTACT_GROUP_NOT_FOUND,
        
        /// <remarks/>
        CONTACT_GROUP_ACCESS_DENIED,
        
        /// <remarks/>
        CONTACT_ITEM_NOT_FOUND,
        
        /// <remarks/>
        CONTACT_ITEM_ACCESS_DENIED,
        
        /// <remarks/>
        CONTACT_NUMBER_IN_USE,
        
        /// <remarks/>
        NUMBER_ITEM_EXISTS,
        
        /// <remarks/>
        STORAGE_ALREADY_CONNECTED,
        
        /// <remarks/>
        STORAGE_REVOKE_FAILURE,
        
        /// <remarks/>
        STORAGE_NOT_CONNECTED,
        
        /// <remarks/>
        STORAGE_NOT_FOUND,
        
        /// <remarks/>
        INSUFFICIENT_FUNDS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ApiServiceFxiMessage")]
    public enum FaxQuality {
        
        /// <remarks/>
        UNKNOWN,
        
        /// <remarks/>
        BASIC,
        
        /// <remarks/>
        STANDARD,
        
        /// <remarks/>
        FINE,
        
        /// <remarks/>
        SUPER_FINE,
        
        /// <remarks/>
        ULTRA_FINE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ApiServiceFxiMessage")]
    public enum FaxCompression {
        
        /// <remarks/>
        UNKNOWN,
        
        /// <remarks/>
        MH,
        
        /// <remarks/>
        MR,
        
        /// <remarks/>
        MMR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ApiServiceFxiMessage")]
    public partial class FaxFile {
        
        private string fileNameField;
        
        private string fileMimeField;
        
        private long fileSizeField;
        
        private bool fileSizeFieldSpecified;
        
        private string fileCheckField;
        
        private byte[] fileDataField;
        
        /// <remarks/>
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        public string fileMime {
            get {
                return this.fileMimeField;
            }
            set {
                this.fileMimeField = value;
            }
        }
        
        /// <remarks/>
        public long fileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool fileSizeSpecified {
            get {
                return this.fileSizeFieldSpecified;
            }
            set {
                this.fileSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string fileCheck {
            get {
                return this.fileCheckField;
            }
            set {
                this.fileCheckField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] fileData {
            get {
                return this.fileDataField;
            }
            set {
                this.fileDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ApiResponseListFaxes))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ApiResponseItemsCount))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ApiResponseFileDownload))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ApiResponseDocPreview))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ApiResponseObject))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ApiServiceFxiMessage")]
    public partial class ApiResponse {
        
        private StateCodes stateCodeField;
        
        private string stateMessageField;
        
        /// <remarks/>
        public StateCodes stateCode {
            get {
                return this.stateCodeField;
            }
            set {
                this.stateCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string stateMessage {
            get {
                return this.stateMessageField;
            }
            set {
                this.stateMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ApiServiceFxiMessage")]
    public partial class ApiResponseListFaxes : ApiResponse {
        
        private int countResultField;
        
        private bool countResultFieldSpecified;
        
        private int countTotalField;
        
        private bool countTotalFieldSpecified;
        
        private FaxinMessage[] itemsField;
        
        /// <remarks/>
        public int countResult {
            get {
                return this.countResultField;
            }
            set {
                this.countResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool countResultSpecified {
            get {
                return this.countResultFieldSpecified;
            }
            set {
                this.countResultFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int countTotal {
            get {
                return this.countTotalField;
            }
            set {
                this.countTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool countTotalSpecified {
            get {
                return this.countTotalFieldSpecified;
            }
            set {
                this.countTotalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FaxinMessage[] items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ApiServiceFxiMessage")]
    public partial class ApiResponseItemsCount : ApiResponse {
        
        private int itemsCountField;
        
        private bool itemsCountFieldSpecified;
        
        /// <remarks/>
        public int itemsCount {
            get {
                return this.itemsCountField;
            }
            set {
                this.itemsCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool itemsCountSpecified {
            get {
                return this.itemsCountFieldSpecified;
            }
            set {
                this.itemsCountFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ApiResponseDocPreview))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ApiServiceFxiMessage")]
    public partial class ApiResponseFileDownload : ApiResponse {
        
        private FaxFile documentField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public FaxFile Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ApiServiceFxiMessage")]
    public partial class ApiResponseDocPreview : ApiResponseFileDownload {
        
        private int pagesField;
        
        private bool pagesFieldSpecified;
        
        /// <remarks/>
        public int pages {
            get {
                return this.pagesField;
            }
            set {
                this.pagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool pagesSpecified {
            get {
                return this.pagesFieldSpecified;
            }
            set {
                this.pagesFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ApiServiceFxiMessage")]
    public partial class ApiResponseObject : ApiResponse {
        
        private string objectRefField;
        
        /// <remarks/>
        public string objectRef {
            get {
                return this.objectRefField;
            }
            set {
                this.objectRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ApiServiceFxiMessage")]
    public partial class ListPagination {
        
        private int pageNumberField;
        
        private int pageSizeField;
        
        /// <remarks/>
        public int pageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                this.pageNumberField = value;
            }
        }
        
        /// <remarks/>
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ApiRequestListFaxes))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ApiServiceFxiMessage")]
    public partial class ApiRequestCountFaxes {
        
        private string didE164Field;
        
        private System.DateTime dateFromField;
        
        private bool dateFromFieldSpecified;
        
        private System.DateTime dateTillField;
        
        private bool dateTillFieldSpecified;
        
        private bool isSuccessField;
        
        private bool isSuccessFieldSpecified;
        
        private bool hasFileField;
        
        private bool hasFileFieldSpecified;
        
        /// <remarks/>
        public string didE164 {
            get {
                return this.didE164Field;
            }
            set {
                this.didE164Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dateFrom {
            get {
                return this.dateFromField;
            }
            set {
                this.dateFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool dateFromSpecified {
            get {
                return this.dateFromFieldSpecified;
            }
            set {
                this.dateFromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dateTill {
            get {
                return this.dateTillField;
            }
            set {
                this.dateTillField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool dateTillSpecified {
            get {
                return this.dateTillFieldSpecified;
            }
            set {
                this.dateTillFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool isSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                this.isSuccessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool isSuccessSpecified {
            get {
                return this.isSuccessFieldSpecified;
            }
            set {
                this.isSuccessFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool hasFile {
            get {
                return this.hasFileField;
            }
            set {
                this.hasFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool hasFileSpecified {
            get {
                return this.hasFileFieldSpecified;
            }
            set {
                this.hasFileFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ApiServiceFxiMessage")]
    public partial class ApiRequestListFaxes : ApiRequestCountFaxes {
        
        private ListPagination paginationField;
        
        /// <remarks/>
        public ListPagination pagination {
            get {
                return this.paginationField;
            }
            set {
                this.paginationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void countFaxesCompletedEventHandler(object sender, countFaxesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class countFaxesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal countFaxesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApiResponseItemsCount Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApiResponseItemsCount)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void listFaxesCompletedEventHandler(object sender, listFaxesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listFaxesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listFaxesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApiResponseListFaxes Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApiResponseListFaxes)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void downloadFaxCompletedEventHandler(object sender, downloadFaxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class downloadFaxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal downloadFaxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApiResponseDocPreview Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApiResponseDocPreview)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void deleteFaxCompletedEventHandler(object sender, deleteFaxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteFaxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteFaxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApiResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApiResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591